#################
# LEMP PLAYBOOK #
#################
---
- hosts: "all" # применяем команды ко всем хостам из inventory
  become: true # становимся привилегированным пользователем
  tasks: # список тасков
  # NGINX
  - name: "Install" # имя, обязательно для любой таски из плейбука, должно содержать описание того что эта таска делает
    apt: # имя модуля, этот модуль устанавливает софт на хосте с помощью пакета apt
      name: "nginx" # имя пакета для установки
      state: "latest" # установить последнюю версию пакета, в отличие от present, если пакет уже установлен в системе, попробует его обновить
      update_cache: true # вызвать apt update перед установкой, чтобы убедиться в наличии самой свежей базы данных о пакетах

  - name: "Reload nginx"
    service:
      name: "nginx"
      state: "reloaded"
